services:
  - type: web
    name: midsem-project
    runtime: node
    plan: free
    buildCommand: |
      cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM
        value: onboarding@resend.dev
